# Generated by Django 2.0.2 on 2018-03-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20180307_1754'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='login1',
        ),
    ]
