# Generated by Django 2.0.2 on 2018-03-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20180307_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
    ]
